dubbo:
  application:
    name: shipping-server # 注册服务名
  registry:
    address: zookeeper://127.0.0.1:2181
    #address: nacos://127.0.0.1:8848 # 注册中心地址
  protocol:
    name: dubbo # 协议
    port: 20881 # 协议端口
  monitor:
    protocol: registry # 监控中心地址，去注册中心自动发现

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 5678
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082